feat: filter functionality working
frappe/changemakers pull request #57
Opened 2023-05-11 19:55 UTC by harshtandiya

Filters are now working!
User can filter the rescue based on age and gender.

2023-05-11 23:53 UTC, NagariaHussain commented
Maybe add a GIF/Video in the PR description?

2023-05-12 05:45 UTC, harshtandiya commented
> Maybe add a GIF/Video in the PR description?

GIF of the app?

2023-05-12 06:33 UTC, NagariaHussain commented
Yeah, showing how filters work, easier to review in case of PRs that introduce or improve UI.

2023-05-12 09:14 UTC, harshtandiya commented
@NagariaHussain  Done. Please check the description again 😄

2023-05-12 09:18 UTC, NagariaHussain commented
Awesome!

2023-05-12 09:18 UTC, NagariaHussain commented
Awesome!

2023-05-14 19:21 UTC, harshtandiya commented
@NagariaHussain Plz merge 🥺🙏

2023-05-15 00:04 UTC, NagariaHussain commented
Let's do a cleanup of List component today and merge.

2023-05-16 07:50 UTC, NagariaHussain requested changes

2023-05-16 07:50 UTC, NagariaHussain commented on frontend/src/views/rescue/List.vue
> +
Better to use `reactive` instead of multiple refs.

So:
```js
const filters = reactive({
    gender: "",
    ...
})
```

2023-05-16 07:50 UTC, NagariaHussain commented on frontend/src/views/rescue/List.vue
> +const closeFilters = (event) => {
```suggestion
const closeFiltersDialog = (event) => {
```

2023-05-16 07:50 UTC, NagariaHussain commented on frontend/src/views/rescue/List.vue
> +								<div class="flex justify-center gap-0">
```suggestion
								<div class="flex justify-center gap-0">
```

Does `gap-0` have any effect on UI?

2023-05-16 07:50 UTC, NagariaHussain commented on frontend/src/views/rescue/List.vue
> +const closeFilters = (event) => {
You can also do it inline, like you have done for show dialog.

2023-05-16 14:55 UTC, harshtandiya commented
@NagariaHussain Changes made as suggested

2023-05-16 15:42 UTC, merged